server.port: 8082

impl-postfix: H2Impl

spring:
  flyway:
    baseline-on-migrate: true
    enabled: true 
    locations: classpath:db/migration/{vendor}
    out-of-order: false
    table: atm-schema-version
    validate-on-migrate: false
    
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    database-platform: org.hibernate.dialect.H2Dialect    
