---
server.port: 8082

spring:
  flyway:
    baseline-on-migrate: true
    enabled: true 
    locations: classpath:db/migration/{vendor}
    out-of-order: false
    table: atm-schema-version
    validate-on-migrate: false

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
---

spring:
  config.activate.on-profile: mysql
 
  r2dbc: 
    properties.sslMode: TRUST  
    properties.tlsVersion: TLSv1.2   
    properties.allowPublicKeyRetrieval: true       