apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: atm-locator
  namespace: workloads
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: atm-locator
spec:
  env:
    - name: spring_profiles_active
      value: static-search
  build:
    env:
      - name: BP_JVM_VERSION
        value: 17
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://gitlab.eng.vmware.com/tap-scenario-apps/atm-locator-backend
      ref:
        branch: main
    subPath: atm-locator
