---
server:
  forward-headers-strategy: framework

services:
  location-transation:
    identifier:  location-translator
  atm:
    identifier:  atm
  branch:
    identifier:  branch

spring:
  cache:
    cache-names: geolocation
    caffeine:
      spec: maximumSize=100,expireAfterAccess=3600s

springdoc:
  packages-to-scan: com.example.tanzu.atmloc.resources
  api-docs.path: '/api-docs'
  
---

spring:
  config.activate.on-profile: local
  
services:
  location-transation:
    identifier:  'http://localhost:8081'
  atm:
    identifier:  'http://localhost:8082'
  branch:
    identifier:  'http://localhost:8085'
