apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: location-translator
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: location-translator
spec:
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http  
  env: 
  - name: GEOCODIO_API_KEY
    value: DEMO
  source:      
    git:
      url: https://gitlab.eng.vmware.com/tap-scenario-apps/atm-locator-backend
      ref:
        branch: main
    subPath: location-translator
